services:
  nginx:
    container_name: nginx  
    image: nginx:latest
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/ssl:/etc/ssl
    networks:
      - hypertube-net
    depends_on:
      - frontend
      - backend-api
      - backend-user

  frontend:
    container_name: frontend
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        NEXT_PUBIC_HOSTNAME: ${NEXT_PUBLIC_HOSTNAME}
    ports:
      - "4000:4000"
    # volumes:
    #   - ./services/frontend:/app
    #   - /app/node_modules #il faut le traiter avec les variable d'env sinon pb de droits
    networks:
      - hypertube-net
    stdin_open: true
    tty: true

  backend-api:
    container_name: backend-api
    build: ./services/backend-api
    expose:
      - 5000
    env_file:
      - .env
    volumes:
      - ./services/backend-api:/app
    networks:
      - hypertube-net

  backend-user:
    container_name: backend-user
    build: ./services/backend-user
    expose:
      - 6000
    env_file:
      - .env
    volumes:
      - ./services/backend-user:/app
    networks:
      - hypertube-net
    depends_on:
      postgresql:
        condition: service_healthy


  backend-scraper:
    container_name: backend-scraper
    build: ./services/backend-scraper
    expose:
      - 8000
    volumes:
      - ./services/backend-scraper:/app
    networks:
      - hypertube-net
    # depends_on:
    #   postgresql:
    #     condition: service_healthy
  backend-movies:
    container_name: backend-movies
    build: ./services/backend-movies
    expose:
      - 7000
    volumes:
      - ./services/backend-movies:/app
    networks:
      - hypertube-net
    env_file:
      - .env
    # depends_on:
    #   postgresql:
    #     condition: service_healthy


  postgresql:
    container_name: postgresql
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - hypertube-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./services/pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - hypertube-net
    depends_on:
      - postgresql


networks:
  hypertube-net:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgadmin-data:
    driver: local
