services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
    networks:
      - hypertube-net

  backend-api:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - hypertube-net

  streamer:
    container_name: stream
    build: ./streamer
    volumes:
      - ./videos:/app/videos
    depends_on:
      - backend-api
    networks:
      - hypertube-net

  nginx:
    container_name: server
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend-api
    networks:
      - hypertube-net

  db:
    container_name: db
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hypertube
    networks:
      - hypertube-net

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - hypertube-net

networks:
  hypertube-net:

volumes:
  pgdata:
