import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from './components/header.module.css';
import Header from './components/header'
import getTranslations from '@/lib/getTranslations';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {

  const {lang} = await params;
  const t = getTranslations(lang);

  return (
    <html lang={lang}>

      {/* ------------------------------- BODY ----------------------------*/}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header lang={lang as 'en' | 'fr'} />
        {children}
        <footer className={styles.footer}>{t.rightsreserved}</footer>
      </body>
      {/*----------------------------- FOOTER -----------------------------*/}
    </html>
  );
}

