import { use } from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from './components/header.module.css';
import Header from './components/header.tsx'
import translations from '@/locales';
import getTranslations from '@/lib/getTranslations';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {

  const { lang } = use(params);
  const t = getTranslations(lang);

  return (
    <html lang={lang}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Monoton&family=Oswald:wght@400;700&family=Source+Sans+Pro:wght@300;400&display=swap"
          rel="stylesheet"
        />
      </head>

      {/* ------------------------------- BODY ----------------------------*/}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header lang={lang} />
        {children}
        <footer className={styles.footer}>{t.rightsreserved}</footer>
      </body>
      {/*----------------------------- FOOTER -----------------------------*/}
    </html>
  );
}

